# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:
   secrets:
      TEST_SECRET:
        required: true

     

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: Test
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Variable Substitution
       uses: microsoft/variable-substitution@v1
       with:
        files: folder/app.json  
       env:
        Name:  ${{ inputs.name }} 
        Location: ${{ secrets.LOCATION }}
     
     - name: Read Json
       run: cat appsettings.json
      
     - name: Check if secret exist
       run: |
          if [ "${{ secrets.TEST_SECRET }}" == "123" ]; then
            echo "Match"
          else
            echo "Not matched"
          fi
  # This workflow contains a single job called "greet"
  Job2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
    - name: Send greeting to Secrets
      run: echo ${{secrets.NAME}} | sed 's/./& /g'
